name: Ejecutar mi Script Automático

on:
  push:
    branches:
      - main

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Darle permisos de ejecución al script
        run: chmod +x actualizar_fondo.sh

      - name: Ejecutar el script de Bash
        run: ./actualizar_fondo.sh

      - name: Guardar los cambios automáticamente en GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fondo.png
          git commit -m "Fondo actualizado por el script automático" || exit 0
          git push
